#theme: readthedocs
site_name: 不想学习boy的博客
site_description: python相关知识
copyright: Copyright © 2023 [XiaoXie]
nav:
  - 主页: index.md
  - flask:
    - flask基础: flask/day1.md
    - flask进阶: flask/day2.md
    - flask面试题: flask/day3.md
  - django:
    - day1: django/test.md

markdown_extentions:
  - admonition

plugins:
  - search

extra_css:
  - resources/css/extra.css