#theme: readthedocs
site_name: 不想学习boy的博客
site_description: 算法的python实现
copyright: Copyright © 2023 [XiaoXie]
nav:
  - 主页: index.md
  - flask:
    - day1: flask/day1.md
    - day2: flask/day2.md
  - django:
    - day1: django/test.md

markdown_extentions:
  - admonition

plugins:
  - search

extra_css:
  - resources/css/extra.css